# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: DevContainer Release
description: This workflow creates a semantic version release when main changed since the last release tag.
on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:
permissions:
  contents: read # for checkout
jobs:
  release:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    name: release
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.run-semantic-release.outputs.tag_name }}
    container:
      image: mcr.microsoft.com/devcontainers/javascript-node:4-24
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # this should have been done by the checkout action, but it doesn't work in a container, see https://github.com/actions/checkout/issues/766
      - run: git config --global --add safe.directory $PWD
      # pinned version updated automatically by Dependabot.
      # details at https://semantic-release.gitbook.io/semantic-release/usage/installation#global-installation
      - id: run-semantic-release
        run: |
          set -eux pipefail
          npx semantic-release@25.0.1 >> /tmp/semantic-release.log 2>&1 || (cat /tmp/semantic-release.log && exit 1)
          cat /tmp/semantic-release.log
          tag_name=$(grep "Created tag" /tmp/semantic-release.log | sed -E 's/.*Created tag (.*)/\1/')
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: release
    if: needs.release.outputs.tag_name != ''
    name: publish
    runs-on: ubuntu-latest
    steps:
      - run: echo "workflow called"
      - run: |
          echo "triggered by event: ${{ github.event_name }}"
      - run: |
          echo "github object: ${{ toJson(github) }}"
      - run: |
          echo "tag name: ${{ needs.release.outputs.tag_name }}"
 